// "The Board" departure-board design-system primitives.
export { T } from "./tokens";
export type { BoardTokens } from "./tokens";
export { Board, Rivets } from "./Board";
export type { BoardProps } from "./Board";
export { Cap } from "./Cap";
export type { CapProps } from "./Cap";
export { Num } from "./Num";
export type { NumProps, NumSize } from "./Num";
export { SplitFlap } from "./SplitFlap";
export type { SplitFlapProps, FlapSize } from "./SplitFlap";
export { StatusDot } from "./StatusDot";
export type { StatusDotProps } from "./StatusDot";
export { Ticker } from "./Ticker";
export type { TickerProps } from "./Ticker";
export { BoardPageHeader } from "./BoardPageHeader";
export type { BoardPageHeaderProps } from "./BoardPageHeader";
export { BoardListHeader } from "./BoardListHeader";
export type { BoardListHeaderProps } from "./BoardListHeader";
export { Bar } from "./Bar";
export type { BarProps, BarTone } from "./Bar";
export { Pill } from "./Pill";
export type { PillProps, PillTone } from "./Pill";
export { FlapTile } from "./FlapTile";
export type { FlapTileProps, FlapTileTone } from "./FlapTile";
export { ComparisonCard } from "./ComparisonCard";
export type { ComparisonCardProps, ComparisonDir } from "./ComparisonCard";
export { RadialProgress } from "./RadialProgress";
export type { RadialProgressProps, RadialTone } from "./RadialProgress";
export { AnimatedNumber } from "./AnimatedNumber";
export type { AnimatedNumberProps } from "./AnimatedNumber";
export { EmptyState } from "./EmptyState";
export type { EmptyStateProps } from "./EmptyState";
// Jarvis orb (lazy three.js — `three` is not pulled into the main bundle).
export { JarvisOrbView } from "./jarvis/JarvisOrbView";
export type { JarvisOrbViewProps } from "./jarvis/JarvisOrbView";
