// src/features/close-kpi/config/widget-registry.ts
// Widget type metadata, default configs, and the full metric catalog

import type {
  WidgetType,
  WidgetSize,
  WidgetConfig,
  MetricDefinition,
  MetricCategory,
  Metric,
  StatCardConfig,
  StatusDistributionConfig,
  SmartViewMonitorConfig,
  LifecycleTrackerConfig,
  ActivityTimelineConfig,
  CrossReferenceConfig,
  OpportunitySummaryConfig,
  CallAnalyticsConfig,
  CustomFieldBreakdownConfig,
  VmRateSmartViewConfig,
} from "../types/close-kpi.types";

// ─── Widget Registry ───────────────────────────────────────────────

export interface WidgetRegistryEntry {
  type: WidgetType;
  label: string;
  description: string;
  category: MetricCategory;
  icon: string;
  defaultSize: WidgetSize;
  allowedSizes: WidgetSize[];
  colSpan: Record<WidgetSize, number>;
  defaultConfig: WidgetConfig;
  /** If true, widget is not yet implemented and should be hidden from the picker */
  comingSoon?: boolean;
}

const DEFAULT_BASE = {
  dateRange: "this_month" as const,
  comparison: "none" as const,
};

export const WIDGET_REGISTRY: Record<WidgetType, WidgetRegistryEntry> = {
  stat_card: {
    type: "stat_card",
    label: "Stat Card",
    description: "Single KPI metric with trend comparison",
    category: "leads",
    icon: "Hash",
    defaultSize: "small",
    allowedSizes: ["small", "medium"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      metric: "lead_count",
      comparison: "previous_period",
    } satisfies StatCardConfig,
  },
  status_distribution: {
    type: "status_distribution",
    label: "Status Distribution",
    description: "Lead counts by status, source, or custom field",
    category: "leads",
    icon: "BarChart3",
    defaultSize: "medium",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      groupBy: "status",
      sortOrder: "count_desc",
    } satisfies StatusDistributionConfig,
  },
  smart_view_monitor: {
    type: "smart_view_monitor",
    label: "Smart View Monitor",
    description: "Track lead counts across smart views with status breakdown",
    category: "leads",
    icon: "Eye",
    defaultSize: "large",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    comingSoon: true,
    defaultConfig: {
      ...DEFAULT_BASE,
      smartViewIds: [],
      statusIds: [],
    } satisfies SmartViewMonitorConfig,
  },
  call_analytics: {
    type: "call_analytics",
    label: "Call Analytics",
    description:
      "Call volume, duration, connect rate, and disposition breakdown",
    category: "calls",
    icon: "Phone",
    defaultSize: "medium",
    allowedSizes: ["small", "medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      metric: "calls_total",
      direction: "all",
      dateRange: "this_week",
    } satisfies CallAnalyticsConfig,
  },
  activity_timeline: {
    type: "activity_timeline",
    label: "Activity Timeline",
    description: "Calls, emails, and SMS volume over time",
    category: "email_sms",
    icon: "Activity",
    defaultSize: "medium",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    comingSoon: true,
    defaultConfig: {
      ...DEFAULT_BASE,
      activityTypes: ["call", "email", "sms"],
      timeBucket: "day",
      direction: "all",
      dateRange: "this_week",
    } satisfies ActivityTimelineConfig,
  },
  opportunity_summary: {
    type: "opportunity_summary",
    label: "Opportunity Funnel",
    description: "Pipeline value, win rate, sales velocity, and deal metrics",
    category: "opportunities",
    icon: "TrendingUp",
    defaultSize: "medium",
    allowedSizes: ["small", "medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      metric: "pipeline_value" as const,
      statusType: "active",
    } satisfies OpportunitySummaryConfig,
  },
  lifecycle_tracker: {
    type: "lifecycle_tracker",
    label: "Lifecycle Velocity",
    description: "Time between status transitions — find bottlenecks",
    category: "lifecycle",
    icon: "Timer",
    defaultSize: "medium",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      metric: "time_to_first_contact" as const,
      fromStatus: "New",
      toStatus: null,
    } satisfies LifecycleTrackerConfig,
  },
  cross_reference: {
    type: "cross_reference",
    label: "Cross-Reference Matrix",
    description:
      "Smart view rows vs status columns — where do your leads stand",
    category: "leads",
    icon: "Grid3X3",
    defaultSize: "large",
    allowedSizes: ["large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    comingSoon: true,
    defaultConfig: {
      ...DEFAULT_BASE,
      smartViewIds: [],
      statusIds: [],
    } satisfies CrossReferenceConfig,
  },
  custom_field_breakdown: {
    type: "custom_field_breakdown",
    label: "Custom Field Breakdown",
    description:
      "Group leads by any custom field — carriers, policy status, agent, etc.",
    category: "insurance",
    icon: "Tag",
    defaultSize: "medium",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    comingSoon: true,
    defaultConfig: {
      ...DEFAULT_BASE,
      customFieldKey: "",
      aggregation: "count",
      sortOrder: "count_desc",
    } satisfies CustomFieldBreakdownConfig,
  },
  vm_rate_smart_view: {
    type: "vm_rate_smart_view",
    label: "VM Rate by Smart View",
    description:
      "First-call voicemail rate per smart view — detect bad lead batches early",
    category: "calls",
    icon: "PhoneOff",
    defaultSize: "medium",
    allowedSizes: ["medium", "large"],
    colSpan: { small: 1, medium: 1, large: 2 },
    defaultConfig: {
      ...DEFAULT_BASE,
      smartViewIds: [],
      vmThreshold: 40,
      firstCallOnly: true,
      dateRange: "this_week",
    } satisfies VmRateSmartViewConfig,
  },
};

// ─── Metric Catalog ────────────────────────────────────────────────
// The full list of measurable things from Close CRM

export const METRIC_CATALOG: MetricDefinition[] = [
  // ── Lead Metrics ──
  {
    key: "lead_count",
    label: "Total Leads",
    description: "Count of all leads matching filters",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    unit: "number",
  },
  {
    key: "leads_created",
    label: "Leads Created",
    description: "New leads created in the date range",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    field: "date_created",
    unit: "number",
  },
  {
    key: "leads_by_status",
    label: "Leads by Status",
    description: "Lead count broken down by status",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "lead_status_id",
    unit: "number",
  },
  {
    key: "leads_by_source",
    label: "Leads by Source",
    description: "Lead count broken down by source",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "lead_source",
    unit: "number",
  },
  {
    key: "leads_by_smart_view",
    label: "Leads by Smart View",
    description: "Lead count per saved smart view",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    unit: "number",
  },
  {
    key: "leads_untouched",
    label: "Untouched Leads",
    description: "Leads with zero activities",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    unit: "number",
  },
  {
    key: "leads_by_custom_field",
    label: "Leads by Custom Field",
    description: "Lead count grouped by a custom field value",
    category: "leads",
    aggregationType: "count",
    objectType: "lead",
    unit: "number",
  },

  // ── Call Metrics ──
  {
    key: "calls_total",
    label: "Total Calls",
    description: "All calls in the date range",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    unit: "number",
  },
  {
    key: "calls_inbound",
    label: "Inbound Calls",
    description: "Incoming calls only",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "direction",
    unit: "number",
  },
  {
    key: "calls_outbound",
    label: "Outbound Calls",
    description: "Outgoing calls only",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "direction",
    unit: "number",
  },
  {
    key: "calls_answered",
    label: "Answered Calls",
    description: "Calls with answered disposition",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "disposition",
    unit: "number",
  },
  {
    key: "calls_voicemail",
    label: "Voicemail Calls",
    description: "VM left + VM answered",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "disposition",
    unit: "number",
  },
  {
    key: "calls_missed",
    label: "Missed Calls",
    description: "No-answer + busy + blocked",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "disposition",
    unit: "number",
  },
  {
    key: "call_duration_total",
    label: "Total Call Minutes",
    description: "Sum of all call durations",
    category: "calls",
    aggregationType: "sum",
    objectType: "call",
    field: "duration",
    unit: "minutes",
  },
  {
    key: "call_duration_avg",
    label: "Avg Call Duration",
    description: "Average call length",
    category: "calls",
    aggregationType: "average",
    objectType: "call",
    field: "duration",
    unit: "minutes",
  },
  {
    key: "call_connect_rate",
    label: "Connect Rate",
    description: "Answered calls / total calls",
    category: "calls",
    aggregationType: "computed",
    objectType: "call",
    unit: "percent",
  },
  {
    key: "calls_by_disposition",
    label: "Calls by Disposition",
    description: "Breakdown: answered, VM, no-answer, busy, blocked",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    groupByField: "disposition",
    unit: "number",
  },
  {
    key: "calls_by_direction",
    label: "Calls by Direction",
    description: "Inbound vs outbound split",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    groupByField: "direction",
    unit: "number",
  },
  {
    key: "calls_over_time",
    label: "Calls Over Time",
    description: "Call volume trend",
    category: "calls",
    aggregationType: "count",
    objectType: "call",
    field: "activity_at",
    unit: "number",
  },

  // ── Email & SMS ──
  {
    key: "emails_sent",
    label: "Emails Sent",
    description: "Outgoing emails in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "email",
    field: "direction",
    unit: "number",
  },
  {
    key: "emails_received",
    label: "Emails Received",
    description: "Incoming emails in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "email",
    field: "direction",
    unit: "number",
  },
  {
    key: "emails_total",
    label: "Total Emails",
    description: "All emails in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "email",
    unit: "number",
  },
  {
    key: "emails_over_time",
    label: "Emails Over Time",
    description: "Email volume trend",
    category: "email_sms",
    aggregationType: "count",
    objectType: "email",
    field: "activity_at",
    unit: "number",
  },
  {
    key: "sms_sent",
    label: "SMS Sent",
    description: "Outgoing SMS in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "sms",
    field: "direction",
    unit: "number",
  },
  {
    key: "sms_received",
    label: "SMS Received",
    description: "Incoming SMS in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "sms",
    field: "direction",
    unit: "number",
  },
  {
    key: "sms_total",
    label: "Total SMS",
    description: "All SMS in range",
    category: "email_sms",
    aggregationType: "count",
    objectType: "sms",
    unit: "number",
  },
  {
    key: "sms_over_time",
    label: "SMS Over Time",
    description: "SMS volume trend",
    category: "email_sms",
    aggregationType: "count",
    objectType: "sms",
    field: "activity_at",
    unit: "number",
  },

  // ── Opportunity Metrics ──
  {
    key: "pipeline_value",
    label: "Pipeline Value",
    description: "Total $ value of active opportunities",
    category: "opportunities",
    aggregationType: "sum",
    objectType: "opportunity",
    field: "value",
    unit: "currency",
  },
  {
    key: "pipeline_count",
    label: "Active Opportunities",
    description: "Count of active opportunities",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    unit: "number",
  },
  {
    key: "win_rate",
    label: "Win Rate",
    description: "Won / (won + lost) as percentage",
    category: "opportunities",
    aggregationType: "computed",
    objectType: "opportunity",
    unit: "percent",
  },
  {
    key: "avg_deal_size",
    label: "Avg Deal Size",
    description: "Average opportunity value",
    category: "opportunities",
    aggregationType: "average",
    objectType: "opportunity",
    field: "value",
    unit: "currency",
  },
  {
    key: "sales_velocity",
    label: "Sales Velocity",
    description: "(# opps × avg deal × win rate) / avg time to win",
    category: "opportunities",
    aggregationType: "computed",
    objectType: "opportunity",
    unit: "currency",
  },
  {
    key: "avg_time_to_close",
    label: "Avg Time to Close",
    description: "Days from opportunity created to won",
    category: "opportunities",
    aggregationType: "average",
    objectType: "opportunity",
    unit: "duration_days",
  },
  {
    key: "deals_won",
    label: "Deals Won",
    description: "Number of won deals in range",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    unit: "number",
  },
  {
    key: "deals_lost",
    label: "Deals Lost",
    description: "Number of lost deals in range",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    unit: "number",
  },
  {
    key: "deals_won_value",
    label: "Revenue Won",
    description: "Total $ from won deals",
    category: "opportunities",
    aggregationType: "sum",
    objectType: "opportunity",
    field: "value",
    unit: "currency",
  },
  {
    key: "opps_by_status",
    label: "Opps by Status",
    description: "Opportunity count per pipeline stage",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    groupByField: "opp_status_id",
    unit: "number",
  },
  {
    key: "opps_by_value_bucket",
    label: "Opps by Deal Size",
    description: "Bucketed by opportunity value",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    field: "value",
    unit: "number",
  },
  {
    key: "opps_stalled",
    label: "Stalled Opportunities",
    description: "Deals needing attention",
    category: "opportunities",
    aggregationType: "count",
    objectType: "opportunity",
    unit: "number",
  },

  // ── Lifecycle Metrics ──
  {
    key: "time_to_first_contact",
    label: "Time to First Contact",
    description: "Avg days from New → first Contacted status",
    category: "lifecycle",
    aggregationType: "average",
    objectType: "lead_status_change",
    unit: "duration_days",
  },
  {
    key: "time_to_quote",
    label: "Time to Quote",
    description: "Avg days from creation to Quoted",
    category: "lifecycle",
    aggregationType: "average",
    objectType: "lead_status_change",
    unit: "duration_days",
  },
  {
    key: "time_to_sold",
    label: "Time to Sold",
    description: "Avg days from creation to Sold",
    category: "lifecycle",
    aggregationType: "average",
    objectType: "lead_status_change",
    unit: "duration_days",
  },
  {
    key: "time_to_negative",
    label: "Time to Negative Outcome",
    description: "How fast leads reach bad statuses",
    category: "lifecycle",
    aggregationType: "average",
    objectType: "lead_status_change",
    unit: "duration_days",
  },
  {
    key: "status_conversion_rate",
    label: "Status Conversion Rate",
    description: "% of leads moving from status A → B",
    category: "lifecycle",
    aggregationType: "computed",
    objectType: "lead_status_change",
    unit: "percent",
  },
  {
    key: "custom_status_path",
    label: "Custom Status Path",
    description: "Track time between any two statuses",
    category: "lifecycle",
    aggregationType: "average",
    objectType: "lead_status_change",
    unit: "duration_days",
  },

  // ── Insurance-Specific ──
  {
    key: "leads_by_carrier",
    label: "Leads by Carrier",
    description: "Grouped by Carriers custom field",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Carriers",
    unit: "number",
  },
  {
    key: "leads_by_app_status",
    label: "Leads by Application Status",
    description: "Grouped by Application Status",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Application Status",
    unit: "number",
  },
  {
    key: "leads_by_policy_status",
    label: "Leads by Policy Status",
    description: "Grouped by Policy Status",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Policy Status",
    unit: "number",
  },
  {
    key: "premium_pipeline",
    label: "Premium Pipeline",
    description: "Sum of Annual/Monthly Premium values",
    category: "insurance",
    aggregationType: "sum",
    objectType: "lead",
    field: "custom.Annual Premium",
    unit: "currency",
  },
  {
    key: "face_amount_distribution",
    label: "Face Amount Distribution",
    description: "Coverage amounts being quoted",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Face Amount",
    unit: "number",
  },
  {
    key: "leads_by_agent",
    label: "Leads by Agent",
    description: "Which agents own the most leads",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Agent",
    unit: "number",
  },
  {
    key: "leads_by_campaign",
    label: "Leads by Campaign",
    description: "Which campaigns produce the most leads",
    category: "insurance",
    aggregationType: "count",
    objectType: "lead",
    groupByField: "custom.Campaign Name",
    unit: "number",
  },
];

// ─── Category Definitions ──────────────────────────────────────────

export const WIDGET_CATEGORIES = [
  { id: "leads" as const, label: "Leads" },
  { id: "calls" as const, label: "Calls" },
  { id: "email_sms" as const, label: "Email & SMS" },
  { id: "opportunities" as const, label: "Opportunities" },
  { id: "lifecycle" as const, label: "Lifecycle" },
  { id: "insurance" as const, label: "Insurance" },
] as const;

// ─── Helpers ───────────────────────────────────────────────────────

export function getWidgetColSpan(type: WidgetType, size: WidgetSize): number {
  return WIDGET_REGISTRY[type].colSpan[size];
}

export function getMetricsForCategory(
  category: MetricCategory,
): MetricDefinition[] {
  return METRIC_CATALOG.filter((m) => m.category === category);
}

export function getMetricDefinition(key: Metric): MetricDefinition | undefined {
  return METRIC_CATALOG.find((m) => m.key === key);
}

/** Get metrics that can be used in a stat card (single-value metrics) */
export function getStatCardMetrics(): MetricDefinition[] {
  return METRIC_CATALOG.filter(
    (m) => !m.groupByField || m.aggregationType === "computed",
  );
}
